---
 - name: Generate kubeconfig file for cluster
   hosts: localhost
   gather_facts: no
   vars_prompt:
    - name: "server-ip"
      prompt: "Enter the kubernetes master server IP"
      private: no
      register: serverr-ip

    - name: "set-clusterName"
      prompt: "Enter the cluster name"
      private: no
      register: set-clusterName

    - name: "set-username"
      prompt: "Enter the username"
      private: no
      register: set-username

    - name: "set-passwd"
      prompt: "Enter the passwd"
      register: set-passwd

   tasks:
   - name: Add cluster details
     shell: kubectl config --kubeconfig=base-config set-cluster {{set-clusterName}} --server=https://{{server-ip}}

   - name: Add user details
     shell: kubectl config --kubeconfig=base-config set-credentials {{set-username}} --username={{set-username}} --password={{set-passwd}}

   - name: Setting Contexts
     shell: kubectl config --kubeconfig=base-config set-context {{set-username}} --cluster={{set-clusterName}} --user={{set-username}}

